version: 2
jobs:
  build:
    docker:
      - image: busybox
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: try
          command: |
            whoami
            a=3
            touch a
      - run:
          name: try
          command: |
            echo $a
            ls -la

