version: 2
jobs:
  build:
    docker:
      - image: busybox
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: try
          command: |
            whoami
            a=hello_variable
            touch a
            pwd
            mkdir b
            cd b
      - run:
          name: try
          command: |
            echo $a
            pwd
            ls -la

