version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: update system and install requirements
          command: |
            set -x -e
            sudo apt update
            sudo apt upgrade
            sudo apt install build-essential libgnome-keyring-dev python-setuptools npm
      - run:
          name: clone brave
          command: |
            git clone git@github.com:brave/brave-browser.git
            cd brave-browser
            npm install

