version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: update system and install requirements
          command: |
            set -x -e
            sudo apt update
            sudo apt upgrade
            sudo apt install build-essential libgnome-keyring-dev python-setuptools #npm
            node -v
            npm -v
      - run:
          name: getting brave
          command: |
            set -x -e
            git clone git@github.com:brave/brave-browser.git
            cd brave-browser
            
            npm install
            
            # this takes 30-45 minutes to run
            # the Chromium source is downloaded which has a large history
            npm run init
      - run:
          name: install additional build requirements
          command: |
            set -x -e
            cd brave-browser
            
            sudo apt install lsb-release g++-arm-linux-gnueabihf # need for the following script
            ./src/build/install-build-deps.sh
      - run:
          name: setting to specific versions
          command: |
            set -x -e
            cd brave-browser
            
            git rev-parse HEAD
            git status
            # brave-browser: brave-browser repo
            git reset --hard a58ca03
            git rev-parse HEAD
            git status
            
            cd src # brave-browser/src: chromium repo
            git rev-parse HEAD
            git status
            #git stash save
            #git checkout c69466738e3c046f0b77f51d1c57730dac331398
            git reset --hard c69466738e3c046f0b77f51d1c57730dac331398
            #git stash pop
            git rev-parse HEAD
            git status
            
            cd brave # brave-browser/src/brave: brave-core repo
            git rev-parse HEAD
            git status
            #git reset --hard origin/import-remote-script-nodes
            #git reset --hard 8d798266d2e40fe0b4db5a6a95688eccc8d65c5a
            git reset --hard origin/page-graph-integration
            git rev-parse HEAD
            git status
            
            cd ../v8 # brave-browser/src/v8: v8 repo
            git rev-parse HEAD
            git status
            git checkout 392114613e6fe39b64c7bc7b89bef4b4b123dd67
            #git reset --hard 392114613e6fe39b64c7bc7b89bef4b4b123dd67
            git rev-parse HEAD
            git status
      - run:
          name: applying patches
          command: |
            set -x -e
            cd brave-browser
            
            cd src/v8
            git rev-parse HEAD
            git status
            git apply --ignore-whitespace ../../../page-graph-v8.diff
            git rev-parse HEAD
            git status
            
            cd .. # brave-browser/src: chromium repo
            git rev-parse HEAD
            git status
            ## patching the patch...
            #sed -i '\$-#include "third_party/blink/renderer/core/dom/document.h"$s$-$ $' brave/patches/third_party-blink-renderer-core-dom-comment.cc.patch
            #sed -i 's/@@ -21,15 +21,30 @@/@@ -21,15 +21,31 @@/' brave/patches/third_party-blink-renderer-core-dom-comment.cc.patch
            # applying the patches
            find brave/patches -name "*.patch" | while read LINE; do patch -p1 < $LINE; done
            git rev-parse HEAD
            git status
      - run:
          name: building brave
          command: |
            set -x -e
            cd brave-browser
            
            npm run build -- Release --debug_build=true --official_build=false
